CREATE TYPE "ExecutionStatus" AS ENUM ('Created','Planning','ResourcesReserved','ProcurementPrepared','StaffAssigned','DispatchScheduled','InProgress','CollectionScheduled','Completed','Closed','Cancelled','Archived');
CREATE TYPE "ExecutionControlStatus" AS ENUM ('Pending','Ready','Blocked','InProgress','Completed','Waived','Cancelled');
CREATE TYPE "ExecutionGateDecision" AS ENUM ('Pending','Passed','Failed','Waived');
CREATE TYPE "ExecutionIncidentSeverity" AS ENUM ('Low','Medium','High','Critical','Emergency');
CREATE TYPE "ExecutionIncidentStatus" AS ENUM ('Open','Responding','Contained','Resolved','Closed');

CREATE TABLE "EventExecution" (
 "id" TEXT NOT NULL,"systemNumber" SERIAL NOT NULL,"organizationId" TEXT NOT NULL,"eventId" TEXT NOT NULL,"status" "ExecutionStatus" NOT NULL DEFAULT 'Created',
 "executionPlanVersion" INTEGER NOT NULL DEFAULT 0,"summary" TEXT,"commandCenterActive" BOOLEAN NOT NULL DEFAULT false,"goLiveApprovedByUserId" TEXT,"goLiveApprovedAt" TIMESTAMP(3),
 "completedAt" TIMESTAMP(3),"closedAt" TIMESTAMP(3),"cancelledAt" TIMESTAMP(3),"cancellationReason" TEXT,"archivedAt" TIMESTAMP(3),"createdByUserId" TEXT NOT NULL,
 "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "EventExecution_pkey" PRIMARY KEY("id")
);
CREATE TABLE "ExecutionWorkstream" ("id" TEXT NOT NULL,"eventExecutionId" TEXT NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"objective" TEXT,"ownerUserId" TEXT,"status" "ExecutionControlStatus" NOT NULL DEFAULT 'Pending',"sequence" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ExecutionWorkstream_pkey" PRIMARY KEY("id"));
CREATE TABLE "ExecutionMilestone" ("id" TEXT NOT NULL,"eventExecutionId" TEXT NOT NULL,"workstreamId" TEXT,"key" TEXT NOT NULL,"label" TEXT NOT NULL,"status" "ExecutionControlStatus" NOT NULL DEFAULT 'Pending',"dueAt" TIMESTAMP(3),"completedAt" TIMESTAMP(3),"evidence" JSONB,CONSTRAINT "ExecutionMilestone_pkey" PRIMARY KEY("id"));
CREATE TABLE "ExecutionTask" ("id" TEXT NOT NULL,"eventExecutionId" TEXT NOT NULL,"workstreamId" TEXT,"requirementItemId" TEXT,"assetOperationId" TEXT,"title" TEXT NOT NULL,"description" TEXT,"completionCriteria" TEXT NOT NULL,"assignedUserId" TEXT,"assignedSupplierId" TEXT,"status" "ExecutionControlStatus" NOT NULL DEFAULT 'Pending',"priority" TEXT NOT NULL DEFAULT 'Normal',"plannedStart" TIMESTAMP(3),"plannedEnd" TIMESTAMP(3),"actualStart" TIMESTAMP(3),"actualEnd" TIMESTAMP(3),"completionEvidence" JSONB,"blockedReason" TEXT,"sequence" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ExecutionTask_pkey" PRIMARY KEY("id"));
CREATE TABLE "ExecutionReadinessGate" ("id" TEXT NOT NULL,"eventExecutionId" TEXT NOT NULL,"key" TEXT NOT NULL,"name" TEXT NOT NULL,"category" TEXT NOT NULL,"decision" "ExecutionGateDecision" NOT NULL DEFAULT 'Pending',"required" BOOLEAN NOT NULL DEFAULT true,"criteria" JSONB,"evidence" JSONB,"blockerSummary" TEXT,"assessedByUserId" TEXT,"assessedAt" TIMESTAMP(3),"waivedByUserId" TEXT,"waivedAt" TIMESTAMP(3),"waiverReason" TEXT,CONSTRAINT "ExecutionReadinessGate_pkey" PRIMARY KEY("id"));
CREATE TABLE "ExecutionSiteControl" ("id" TEXT NOT NULL,"eventExecutionId" TEXT NOT NULL,"controlType" TEXT NOT NULL,"area" TEXT,"partyType" TEXT,"partyId" TEXT,"status" "ExecutionControlStatus" NOT NULL DEFAULT 'Pending',"scheduledAt" TIMESTAMP(3),"completedAt" TIMESTAMP(3),"permitReference" TEXT,"evidence" JSONB,"notes" TEXT,CONSTRAINT "ExecutionSiteControl_pkey" PRIMARY KEY("id"));
CREATE TABLE "ExecutionCommissioningCheck" ("id" TEXT NOT NULL,"eventExecutionId" TEXT NOT NULL,"systemType" TEXT NOT NULL,"systemReference" TEXT,"testName" TEXT NOT NULL,"criteria" TEXT NOT NULL,"status" "ExecutionControlStatus" NOT NULL DEFAULT 'Pending',"result" TEXT,"evidence" JSONB,"testedByUserId" TEXT,"witnessedByUserId" TEXT,"testedAt" TIMESTAMP(3),CONSTRAINT "ExecutionCommissioningCheck_pkey" PRIMARY KEY("id"));
CREATE TABLE "ExecutionAcceptance" ("id" TEXT NOT NULL,"eventExecutionId" TEXT NOT NULL,"acceptanceType" TEXT NOT NULL,"acceptedPartyType" TEXT NOT NULL,"acceptedPartyId" TEXT,"decision" "ExecutionGateDecision" NOT NULL DEFAULT 'Pending',"notes" TEXT,"evidence" JSONB,"acceptedByUserId" TEXT,"acceptedAt" TIMESTAMP(3),CONSTRAINT "ExecutionAcceptance_pkey" PRIMARY KEY("id"));
CREATE TABLE "ExecutionRunOfShowItem" ("id" TEXT NOT NULL,"eventExecutionId" TEXT NOT NULL,"sequence" INTEGER NOT NULL,"title" TEXT NOT NULL,"scheduledAt" TIMESTAMP(3) NOT NULL,"durationMinutes" INTEGER,"ownerUserId" TEXT,"supplierId" TEXT,"cueType" TEXT,"dependencyItemId" TEXT,"status" "ExecutionControlStatus" NOT NULL DEFAULT 'Pending',"actualAt" TIMESTAMP(3),"varianceMinutes" INTEGER,"notes" TEXT,CONSTRAINT "ExecutionRunOfShowItem_pkey" PRIMARY KEY("id"));
CREATE TABLE "ExecutionCommandLog" ("id" TEXT NOT NULL,"eventExecutionId" TEXT NOT NULL,"logType" TEXT NOT NULL,"severity" TEXT NOT NULL,"message" TEXT NOT NULL,"relatedType" TEXT,"relatedId" TEXT,"metadata" JSONB,"recordedByUserId" TEXT NOT NULL,"occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ExecutionCommandLog_pkey" PRIMARY KEY("id"));
CREATE TABLE "ExecutionIncident" ("id" TEXT NOT NULL,"systemNumber" SERIAL NOT NULL,"eventExecutionId" TEXT NOT NULL,"incidentType" TEXT NOT NULL,"severity" "ExecutionIncidentSeverity" NOT NULL,"status" "ExecutionIncidentStatus" NOT NULL DEFAULT 'Open',"title" TEXT NOT NULL,"description" TEXT NOT NULL,"location" TEXT,"peopleAtRisk" INTEGER,"responseOwnerUserId" TEXT,"immediateActions" JSONB,"evidence" JSONB,"escalatedAt" TIMESTAMP(3),"containedAt" TIMESTAMP(3),"resolvedAt" TIMESTAMP(3),"closedAt" TIMESTAMP(3),"reportedByUserId" TEXT NOT NULL,"reportedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ExecutionIncident_pkey" PRIMARY KEY("id"));
CREATE TABLE "ExecutionCloseoutItem" ("id" TEXT NOT NULL,"eventExecutionId" TEXT NOT NULL,"closeoutType" TEXT NOT NULL,"referenceType" TEXT,"referenceId" TEXT,"status" "ExecutionControlStatus" NOT NULL DEFAULT 'Pending',"criteria" TEXT NOT NULL,"evidence" JSONB,"completedByUserId" TEXT,"completedAt" TIMESTAMP(3),CONSTRAINT "ExecutionCloseoutItem_pkey" PRIMARY KEY("id"));

CREATE UNIQUE INDEX "EventExecution_systemNumber_key" ON "EventExecution"("systemNumber"); CREATE UNIQUE INDEX "EventExecution_eventId_key" ON "EventExecution"("eventId"); CREATE INDEX "EventExecution_organizationId_status_idx" ON "EventExecution"("organizationId","status"); CREATE INDEX "EventExecution_createdByUserId_idx" ON "EventExecution"("createdByUserId");
CREATE UNIQUE INDEX "ExecutionWorkstream_eventExecutionId_key_key" ON "ExecutionWorkstream"("eventExecutionId","key"); CREATE INDEX "ExecutionWorkstream_eventExecutionId_sequence_idx" ON "ExecutionWorkstream"("eventExecutionId","sequence");
CREATE UNIQUE INDEX "ExecutionMilestone_eventExecutionId_key_key" ON "ExecutionMilestone"("eventExecutionId","key"); CREATE INDEX "ExecutionMilestone_workstreamId_idx" ON "ExecutionMilestone"("workstreamId"); CREATE INDEX "ExecutionMilestone_eventExecutionId_status_dueAt_idx" ON "ExecutionMilestone"("eventExecutionId","status","dueAt");
CREATE INDEX "ExecutionTask_eventExecutionId_status_idx" ON "ExecutionTask"("eventExecutionId","status"); CREATE INDEX "ExecutionTask_workstreamId_sequence_idx" ON "ExecutionTask"("workstreamId","sequence"); CREATE INDEX "ExecutionTask_requirementItemId_idx" ON "ExecutionTask"("requirementItemId"); CREATE INDEX "ExecutionTask_assignedUserId_idx" ON "ExecutionTask"("assignedUserId");
CREATE UNIQUE INDEX "ExecutionReadinessGate_eventExecutionId_key_key" ON "ExecutionReadinessGate"("eventExecutionId","key"); CREATE INDEX "ExecutionReadinessGate_eventExecutionId_decision_required_idx" ON "ExecutionReadinessGate"("eventExecutionId","decision","required");
CREATE INDEX "ExecutionSiteControl_eventExecutionId_controlType_status_idx" ON "ExecutionSiteControl"("eventExecutionId","controlType","status"); CREATE INDEX "ExecutionCommissioningCheck_eventExecutionId_status_idx" ON "ExecutionCommissioningCheck"("eventExecutionId","status"); CREATE INDEX "ExecutionCommissioningCheck_systemType_idx" ON "ExecutionCommissioningCheck"("systemType"); CREATE INDEX "ExecutionAcceptance_eventExecutionId_acceptanceType_decision_idx" ON "ExecutionAcceptance"("eventExecutionId","acceptanceType","decision");
CREATE UNIQUE INDEX "ExecutionRunOfShowItem_eventExecutionId_sequence_key" ON "ExecutionRunOfShowItem"("eventExecutionId","sequence"); CREATE INDEX "ExecutionRunOfShowItem_eventExecutionId_scheduledAt_idx" ON "ExecutionRunOfShowItem"("eventExecutionId","scheduledAt"); CREATE INDEX "ExecutionRunOfShowItem_status_idx" ON "ExecutionRunOfShowItem"("status");
CREATE INDEX "ExecutionCommandLog_eventExecutionId_occurredAt_idx" ON "ExecutionCommandLog"("eventExecutionId","occurredAt"); CREATE INDEX "ExecutionCommandLog_logType_severity_idx" ON "ExecutionCommandLog"("logType","severity");
CREATE UNIQUE INDEX "ExecutionIncident_systemNumber_key" ON "ExecutionIncident"("systemNumber"); CREATE INDEX "ExecutionIncident_eventExecutionId_status_severity_idx" ON "ExecutionIncident"("eventExecutionId","status","severity"); CREATE INDEX "ExecutionIncident_reportedAt_idx" ON "ExecutionIncident"("reportedAt");
CREATE INDEX "ExecutionCloseoutItem_eventExecutionId_status_idx" ON "ExecutionCloseoutItem"("eventExecutionId","status"); CREATE INDEX "ExecutionCloseoutItem_closeoutType_idx" ON "ExecutionCloseoutItem"("closeoutType");

ALTER TABLE "EventExecution" ADD CONSTRAINT "EventExecution_organizationId_fkey" FOREIGN KEY("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "EventExecution" ADD CONSTRAINT "EventExecution_eventId_fkey" FOREIGN KEY("eventId") REFERENCES "Event"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "EventExecution" ADD CONSTRAINT "EventExecution_createdByUserId_fkey" FOREIGN KEY("createdByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ExecutionWorkstream" ADD CONSTRAINT "ExecutionWorkstream_eventExecutionId_fkey" FOREIGN KEY("eventExecutionId") REFERENCES "EventExecution"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ExecutionMilestone" ADD CONSTRAINT "ExecutionMilestone_eventExecutionId_fkey" FOREIGN KEY("eventExecutionId") REFERENCES "EventExecution"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ExecutionMilestone" ADD CONSTRAINT "ExecutionMilestone_workstreamId_fkey" FOREIGN KEY("workstreamId") REFERENCES "ExecutionWorkstream"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ExecutionTask" ADD CONSTRAINT "ExecutionTask_eventExecutionId_fkey" FOREIGN KEY("eventExecutionId") REFERENCES "EventExecution"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ExecutionTask" ADD CONSTRAINT "ExecutionTask_workstreamId_fkey" FOREIGN KEY("workstreamId") REFERENCES "ExecutionWorkstream"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ExecutionReadinessGate" ADD CONSTRAINT "ExecutionReadinessGate_eventExecutionId_fkey" FOREIGN KEY("eventExecutionId") REFERENCES "EventExecution"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ExecutionSiteControl" ADD CONSTRAINT "ExecutionSiteControl_eventExecutionId_fkey" FOREIGN KEY("eventExecutionId") REFERENCES "EventExecution"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ExecutionCommissioningCheck" ADD CONSTRAINT "ExecutionCommissioningCheck_eventExecutionId_fkey" FOREIGN KEY("eventExecutionId") REFERENCES "EventExecution"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ExecutionAcceptance" ADD CONSTRAINT "ExecutionAcceptance_eventExecutionId_fkey" FOREIGN KEY("eventExecutionId") REFERENCES "EventExecution"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ExecutionRunOfShowItem" ADD CONSTRAINT "ExecutionRunOfShowItem_eventExecutionId_fkey" FOREIGN KEY("eventExecutionId") REFERENCES "EventExecution"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ExecutionCommandLog" ADD CONSTRAINT "ExecutionCommandLog_eventExecutionId_fkey" FOREIGN KEY("eventExecutionId") REFERENCES "EventExecution"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ExecutionIncident" ADD CONSTRAINT "ExecutionIncident_eventExecutionId_fkey" FOREIGN KEY("eventExecutionId") REFERENCES "EventExecution"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ExecutionCloseoutItem" ADD CONSTRAINT "ExecutionCloseoutItem_eventExecutionId_fkey" FOREIGN KEY("eventExecutionId") REFERENCES "EventExecution"("id") ON DELETE CASCADE ON UPDATE CASCADE;
