CREATE TYPE "AssetTrackingMode" AS ENUM ('Serialized','Quantity','Batch','Kit');
CREATE TYPE "AssetOwnershipType" AS ENUM ('BusinessOwned','ClientOwned','SupplierOwned','ThirdPartyOwned','Leased','Financed','PendingConfirmation');
CREATE TYPE "AssetCreationSource" AS ENUM ('ManualRegistration','ProcurementPurchase','SupplierHireIntake','ClientAssetIntake','StockImport','ManufacturingCompletion','AssetSplit','BatchReceipt','SystemIntegration','LegacyMigration');
CREATE TYPE "AssetLifecycleStatus" AS ENUM ('PendingIntake','Active','InInspection','InMaintenance','Quarantined','Damaged','Lost','Stolen','WrittenOff','Sold','ReturnedToOwner','Retired','Archived');
CREATE TYPE "AssetMovementType" AS ENUM ('Intake','PutAway','Relocation','Pick','Pack','Stage','Load','Dispatch','Deliver','Deploy','Return','Quarantine','MaintenanceTransfer','Disposal');
CREATE TYPE "AssetOperationStatus" AS ENUM ('Draft','Ready','InProgress','Exception','Completed','Cancelled');
CREATE TYPE "AssetReservationStatus" AS ENUM ('Draft','Reserved','Confirmed','Released','Fulfilled','Cancelled');
CREATE TYPE "AssetInspectionOutcome" AS ENUM ('Pass','PassWithNotes','Fail','Quarantine');
CREATE TYPE "AssetMaintenanceStatus" AS ENUM ('Draft','Approved','Scheduled','InProgress','AwaitingParts','Completed','Cancelled');
CREATE TYPE "AssetIncidentType" AS ENUM ('Damage','Loss','Missing','Theft','Failure');
CREATE TYPE "AssetIncidentStatus" AS ENUM ('Open','Investigating','RecoveryInProgress','Recovered','Resolved','WrittenOff');
CREATE TYPE "AssetDisposalStatus" AS ENUM ('Proposed','Approved','Executed','Cancelled');

CREATE TABLE "AssetDefinition" (
 "id" TEXT NOT NULL,"systemNumber" SERIAL NOT NULL,"organizationId" TEXT NOT NULL,"assetCode" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT,
 "classification" TEXT NOT NULL,"category" TEXT NOT NULL,"subcategory" TEXT,"trackingMode" "AssetTrackingMode" NOT NULL,"ownershipType" "AssetOwnershipType" NOT NULL,
 "ownershipPartyType" TEXT,"ownershipPartyId" TEXT,"unitOfMeasure" TEXT NOT NULL,"creationSource" "AssetCreationSource" NOT NULL,"originatingType" TEXT,"originatingId" TEXT,
 "family" TEXT,"variantAttributes" JSONB,"brand" TEXT,"model" TEXT,"manufacturer" TEXT,"internalSku" TEXT,"supplierSku" TEXT,"barcode" TEXT,"dimensions" TEXT,"weight" TEXT,
 "material" TEXT,"colour" TEXT,"finish" TEXT,"handlingRequirements" TEXT,"replacementValue" DOUBLE PRECISION,"capabilityTags" TEXT[] DEFAULT ARRAY[]::TEXT[],
 "quantityOnHand" DOUBLE PRECISION NOT NULL DEFAULT 0,"quantityUnavailable" DOUBLE PRECISION NOT NULL DEFAULT 0,"media" JSONB,"active" BOOLEAN NOT NULL DEFAULT true,
 "createdByUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"archivedAt" TIMESTAMP(3),
 CONSTRAINT "AssetDefinition_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "AssetInstance" (
 "id" TEXT NOT NULL,"systemNumber" SERIAL NOT NULL,"organizationId" TEXT NOT NULL,"assetDefinitionId" TEXT NOT NULL,"operationalCode" TEXT NOT NULL,"manufacturerSerial" TEXT,
 "lifecycleStatus" "AssetLifecycleStatus" NOT NULL DEFAULT 'PendingIntake',"ownershipType" "AssetOwnershipType" NOT NULL,"creationSource" "AssetCreationSource" NOT NULL,
 "qrIdentity" TEXT,"barcodeIdentity" TEXT,"nfcIdentity" TEXT,"acquisitionDate" TIMESTAMP(3),"commissioningDate" TIMESTAMP(3),"warrantyExpiryDate" TIMESTAMP(3),
 "replacementValue" DOUBLE PRECISION,"conditionGrade" TEXT,"currentLocationId" TEXT,"currentCustodianType" TEXT,"currentCustodianId" TEXT,"controlStartDate" TIMESTAMP(3),
 "expectedControlEndDate" TIMESTAMP(3),"actualControlEndDate" TIMESTAMP(3),"sourceAgreementReference" TEXT,"parentInstanceId" TEXT,"createdByUserId" TEXT NOT NULL,
 "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"archivedAt" TIMESTAMP(3), CONSTRAINT "AssetInstance_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "AssetBatch" ("id" TEXT NOT NULL,"systemNumber" SERIAL NOT NULL,"organizationId" TEXT NOT NULL,"assetDefinitionId" TEXT NOT NULL,"quantityReceived" DOUBLE PRECISION NOT NULL,"quantityBalance" DOUBLE PRECISION NOT NULL,"originReference" TEXT,"attributes" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "AssetBatch_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetKit" ("id" TEXT NOT NULL,"systemNumber" SERIAL NOT NULL,"organizationId" TEXT NOT NULL,"assetDefinitionId" TEXT NOT NULL,"name" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "AssetKit_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetKitMember" ("id" TEXT NOT NULL,"assetKitId" TEXT NOT NULL,"memberType" TEXT NOT NULL,"memberId" TEXT NOT NULL,"quantity" DOUBLE PRECISION NOT NULL DEFAULT 1,"effectiveFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"effectiveTo" TIMESTAMP(3),"required" BOOLEAN NOT NULL DEFAULT true,CONSTRAINT "AssetKitMember_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetIdentityAudit" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"entityType" TEXT NOT NULL,"entityId" TEXT NOT NULL,"action" TEXT NOT NULL,"previousValue" JSONB,"newValue" JSONB,"reason" TEXT,"sourceAction" TEXT NOT NULL,"relatedType" TEXT,"relatedId" TEXT,"userId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AssetIdentityAudit_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetLocation" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"storageLocationId" TEXT,"parentLocationId" TEXT,"code" TEXT NOT NULL,"name" TEXT NOT NULL,"locationType" TEXT NOT NULL,"barcode" TEXT,"qrIdentity" TEXT,"capacity" DOUBLE PRECISION,"capacityUnit" TEXT,"handlingRules" JSONB,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "AssetLocation_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetMovement" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"assetEntityType" TEXT NOT NULL,"assetEntityId" TEXT NOT NULL,"movementType" "AssetMovementType" NOT NULL,"quantity" DOUBLE PRECISION NOT NULL DEFAULT 1,"fromLocationId" TEXT,"toLocationId" TEXT,"fromCustodianType" TEXT,"fromCustodianId" TEXT,"toCustodianType" TEXT,"toCustodianId" TEXT,"eventId" TEXT,"referenceType" TEXT,"referenceId" TEXT,"reason" TEXT,"evidence" JSONB,"performedByUserId" TEXT NOT NULL,"occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AssetMovement_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetQrEvent" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"qrIdentity" TEXT NOT NULL,"assetEntityType" TEXT NOT NULL,"assetEntityId" TEXT NOT NULL,"action" TEXT NOT NULL,"locationId" TEXT,"eventId" TEXT,"deviceId" TEXT,"offlineRecordedAt" TIMESTAMP(3),"synchronizedAt" TIMESTAMP(3),"latitude" DOUBLE PRECISION,"longitude" DOUBLE PRECISION,"evidence" JSONB,"scannedByUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AssetQrEvent_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetReservation" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"eventId" TEXT NOT NULL,"requirementItemId" TEXT NOT NULL,"assetDefinitionId" TEXT NOT NULL,"assetInstanceId" TEXT,"quantity" DOUBLE PRECISION NOT NULL,"startDateTime" TIMESTAMP(3) NOT NULL,"endDateTime" TIMESTAMP(3) NOT NULL,"status" "AssetReservationStatus" NOT NULL DEFAULT 'Draft',"priority" INTEGER NOT NULL DEFAULT 0,"overrideReason" TEXT,"approvedByUserId" TEXT,"approvedAt" TIMESTAMP(3),"createdByUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "AssetReservation_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetOperation" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"eventId" TEXT,"operationType" TEXT NOT NULL,"status" "AssetOperationStatus" NOT NULL DEFAULT 'Draft',"sourceLocationId" TEXT,"targetLocationId" TEXT,"assignedTeamId" TEXT,"plannedStart" TIMESTAMP(3),"plannedEnd" TIMESTAMP(3),"actualStart" TIMESTAMP(3),"actualEnd" TIMESTAMP(3),"approvedByUserId" TEXT,"approvedAt" TIMESTAMP(3),"exceptionNotes" TEXT,"createdByUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "AssetOperation_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetOperationLine" ("id" TEXT NOT NULL,"assetOperationId" TEXT NOT NULL,"requirementItemId" TEXT,"assetEntityType" TEXT NOT NULL,"assetEntityId" TEXT NOT NULL,"quantityPlanned" DOUBLE PRECISION NOT NULL,"quantityCompleted" DOUBLE PRECISION NOT NULL DEFAULT 0,"sequence" INTEGER NOT NULL DEFAULT 0,"verificationMethod" TEXT,"evidence" JSONB,CONSTRAINT "AssetOperationLine_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetDeployment" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"eventId" TEXT NOT NULL,"requirementItemId" TEXT,"assetEntityType" TEXT NOT NULL,"assetEntityId" TEXT NOT NULL,"quantity" DOUBLE PRECISION NOT NULL DEFAULT 1,"deploymentArea" TEXT,"setupStatus" TEXT NOT NULL,"deployedAt" TIMESTAMP(3),"verifiedAt" TIMESTAMP(3),"returnedAt" TIMESTAMP(3),"custodianUserId" TEXT,"conditionAtDeploy" TEXT,"conditionAtReturn" TEXT,"evidence" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "AssetDeployment_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetInspection" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"assetEntityType" TEXT NOT NULL,"assetEntityId" TEXT NOT NULL,"inspectionType" TEXT NOT NULL,"outcome" "AssetInspectionOutcome" NOT NULL,"checklistVersion" TEXT,"responses" JSONB,"conditionGrade" TEXT,"notes" TEXT,"evidence" JSONB,"eventId" TEXT,"performedByUserId" TEXT NOT NULL,"performedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AssetInspection_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetMaintenanceWorkOrder" ("id" TEXT NOT NULL,"systemNumber" SERIAL NOT NULL,"organizationId" TEXT NOT NULL,"assetEntityType" TEXT NOT NULL,"assetEntityId" TEXT NOT NULL,"maintenanceType" TEXT NOT NULL,"status" "AssetMaintenanceStatus" NOT NULL DEFAULT 'Draft',"priority" TEXT NOT NULL,"description" TEXT NOT NULL,"scheduledStart" TIMESTAMP(3),"scheduledEnd" TIMESTAMP(3),"completedAt" TIMESTAMP(3),"assignedSupplierId" TEXT,"assignedUserId" TEXT,"estimatedCost" DOUBLE PRECISION,"actualCost" DOUBLE PRECISION,"parts" JSONB,"completionNotes" TEXT,"approvedByUserId" TEXT,"approvedAt" TIMESTAMP(3),"createdByUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "AssetMaintenanceWorkOrder_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetIncident" ("id" TEXT NOT NULL,"systemNumber" SERIAL NOT NULL,"organizationId" TEXT NOT NULL,"eventId" TEXT,"assetEntityType" TEXT NOT NULL,"assetEntityId" TEXT NOT NULL,"incidentType" "AssetIncidentType" NOT NULL,"status" "AssetIncidentStatus" NOT NULL DEFAULT 'Open',"quantity" DOUBLE PRECISION NOT NULL DEFAULT 1,"occurredAt" TIMESTAMP(3) NOT NULL,"reportedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"locationId" TEXT,"custodianType" TEXT,"custodianId" TEXT,"description" TEXT NOT NULL,"evidence" JSONB,"estimatedLoss" DOUBLE PRECISION,"recoveryAmount" DOUBLE PRECISION,"liabilityPartyType" TEXT,"liabilityPartyId" TEXT,"resolutionNotes" TEXT,"reportedByUserId" TEXT NOT NULL,"resolvedByUserId" TEXT,"resolvedAt" TIMESTAMP(3),CONSTRAINT "AssetIncident_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetDisposal" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"assetEntityType" TEXT NOT NULL,"assetEntityId" TEXT NOT NULL,"status" "AssetDisposalStatus" NOT NULL DEFAULT 'Proposed',"disposalMethod" TEXT NOT NULL,"reason" TEXT NOT NULL,"proposedValue" DOUBLE PRECISION,"realisedValue" DOUBLE PRECISION,"proposedByUserId" TEXT NOT NULL,"proposedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"approvedByUserId" TEXT,"approvedAt" TIMESTAMP(3),"executedByUserId" TEXT,"executedAt" TIMESTAMP(3),"evidence" JSONB,CONSTRAINT "AssetDisposal_pkey" PRIMARY KEY("id"));
CREATE TABLE "AssetGovernanceException" ("id" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"exceptionType" TEXT NOT NULL,"severity" TEXT NOT NULL,"entityType" TEXT NOT NULL,"entityId" TEXT NOT NULL,"details" JSONB,"detectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"resolvedAt" TIMESTAMP(3),"resolvedByUserId" TEXT,"resolutionNotes" TEXT,CONSTRAINT "AssetGovernanceException_pkey" PRIMARY KEY("id"));

CREATE UNIQUE INDEX "AssetDefinition_systemNumber_key" ON "AssetDefinition"("systemNumber");
CREATE UNIQUE INDEX "AssetDefinition_organizationId_assetCode_key" ON "AssetDefinition"("organizationId","assetCode");
CREATE UNIQUE INDEX "AssetDefinition_organizationId_barcode_key" ON "AssetDefinition"("organizationId","barcode");
CREATE INDEX "AssetDefinition_organizationId_classification_category_idx" ON "AssetDefinition"("organizationId","classification","category");
CREATE INDEX "AssetDefinition_trackingMode_idx" ON "AssetDefinition"("trackingMode"); CREATE INDEX "AssetDefinition_name_idx" ON "AssetDefinition"("name"); CREATE INDEX "AssetDefinition_archivedAt_idx" ON "AssetDefinition"("archivedAt");
CREATE UNIQUE INDEX "AssetInstance_systemNumber_key" ON "AssetInstance"("systemNumber"); CREATE UNIQUE INDEX "AssetInstance_qrIdentity_key" ON "AssetInstance"("qrIdentity"); CREATE UNIQUE INDEX "AssetInstance_organizationId_operationalCode_key" ON "AssetInstance"("organizationId","operationalCode"); CREATE UNIQUE INDEX "AssetInstance_organizationId_manufacturerSerial_key" ON "AssetInstance"("organizationId","manufacturerSerial");
CREATE INDEX "AssetInstance_organizationId_lifecycleStatus_idx" ON "AssetInstance"("organizationId","lifecycleStatus"); CREATE INDEX "AssetInstance_assetDefinitionId_idx" ON "AssetInstance"("assetDefinitionId"); CREATE INDEX "AssetInstance_currentLocationId_idx" ON "AssetInstance"("currentLocationId"); CREATE INDEX "AssetInstance_archivedAt_idx" ON "AssetInstance"("archivedAt");
CREATE UNIQUE INDEX "AssetBatch_systemNumber_key" ON "AssetBatch"("systemNumber"); CREATE INDEX "AssetBatch_organizationId_idx" ON "AssetBatch"("organizationId"); CREATE INDEX "AssetBatch_assetDefinitionId_idx" ON "AssetBatch"("assetDefinitionId");
CREATE UNIQUE INDEX "AssetKit_systemNumber_key" ON "AssetKit"("systemNumber"); CREATE INDEX "AssetKit_organizationId_idx" ON "AssetKit"("organizationId"); CREATE INDEX "AssetKit_assetDefinitionId_idx" ON "AssetKit"("assetDefinitionId");
CREATE INDEX "AssetKitMember_assetKitId_effectiveTo_idx" ON "AssetKitMember"("assetKitId","effectiveTo"); CREATE INDEX "AssetKitMember_memberType_memberId_idx" ON "AssetKitMember"("memberType","memberId");
CREATE INDEX "AssetIdentityAudit_organizationId_createdAt_idx" ON "AssetIdentityAudit"("organizationId","createdAt"); CREATE INDEX "AssetIdentityAudit_entityType_entityId_createdAt_idx" ON "AssetIdentityAudit"("entityType","entityId","createdAt"); CREATE INDEX "AssetIdentityAudit_userId_idx" ON "AssetIdentityAudit"("userId");
CREATE UNIQUE INDEX "AssetLocation_organizationId_code_key" ON "AssetLocation"("organizationId","code"); CREATE UNIQUE INDEX "AssetLocation_organizationId_qrIdentity_key" ON "AssetLocation"("organizationId","qrIdentity"); CREATE INDEX "AssetLocation_organizationId_active_idx" ON "AssetLocation"("organizationId","active"); CREATE INDEX "AssetLocation_storageLocationId_idx" ON "AssetLocation"("storageLocationId"); CREATE INDEX "AssetLocation_parentLocationId_idx" ON "AssetLocation"("parentLocationId");
CREATE INDEX "AssetMovement_organizationId_occurredAt_idx" ON "AssetMovement"("organizationId","occurredAt"); CREATE INDEX "AssetMovement_assetEntityType_assetEntityId_occurredAt_idx" ON "AssetMovement"("assetEntityType","assetEntityId","occurredAt"); CREATE INDEX "AssetMovement_eventId_idx" ON "AssetMovement"("eventId"); CREATE INDEX "AssetMovement_fromLocationId_idx" ON "AssetMovement"("fromLocationId"); CREATE INDEX "AssetMovement_toLocationId_idx" ON "AssetMovement"("toLocationId");
CREATE INDEX "AssetQrEvent_organizationId_createdAt_idx" ON "AssetQrEvent"("organizationId","createdAt"); CREATE INDEX "AssetQrEvent_qrIdentity_createdAt_idx" ON "AssetQrEvent"("qrIdentity","createdAt"); CREATE INDEX "AssetQrEvent_assetEntityType_assetEntityId_createdAt_idx" ON "AssetQrEvent"("assetEntityType","assetEntityId","createdAt"); CREATE INDEX "AssetQrEvent_eventId_idx" ON "AssetQrEvent"("eventId");
CREATE INDEX "AssetReservation_organizationId_eventId_idx" ON "AssetReservation"("organizationId","eventId"); CREATE INDEX "AssetReservation_requirementItemId_idx" ON "AssetReservation"("requirementItemId"); CREATE INDEX "AssetReservation_assetDefinitionId_startDateTime_endDateTime_status_idx" ON "AssetReservation"("assetDefinitionId","startDateTime","endDateTime","status"); CREATE INDEX "AssetReservation_assetInstanceId_startDateTime_endDateTime_status_idx" ON "AssetReservation"("assetInstanceId","startDateTime","endDateTime","status");
CREATE INDEX "AssetOperation_organizationId_status_idx" ON "AssetOperation"("organizationId","status"); CREATE INDEX "AssetOperation_eventId_operationType_idx" ON "AssetOperation"("eventId","operationType"); CREATE INDEX "AssetOperationLine_assetOperationId_sequence_idx" ON "AssetOperationLine"("assetOperationId","sequence"); CREATE INDEX "AssetOperationLine_assetEntityType_assetEntityId_idx" ON "AssetOperationLine"("assetEntityType","assetEntityId"); CREATE INDEX "AssetOperationLine_requirementItemId_idx" ON "AssetOperationLine"("requirementItemId");
CREATE INDEX "AssetDeployment_organizationId_eventId_idx" ON "AssetDeployment"("organizationId","eventId"); CREATE INDEX "AssetDeployment_assetEntityType_assetEntityId_idx" ON "AssetDeployment"("assetEntityType","assetEntityId"); CREATE INDEX "AssetDeployment_requirementItemId_idx" ON "AssetDeployment"("requirementItemId");
CREATE INDEX "AssetInspection_organizationId_performedAt_idx" ON "AssetInspection"("organizationId","performedAt"); CREATE INDEX "AssetInspection_assetEntityType_assetEntityId_performedAt_idx" ON "AssetInspection"("assetEntityType","assetEntityId","performedAt"); CREATE INDEX "AssetInspection_eventId_idx" ON "AssetInspection"("eventId");
CREATE UNIQUE INDEX "AssetMaintenanceWorkOrder_systemNumber_key" ON "AssetMaintenanceWorkOrder"("systemNumber"); CREATE INDEX "AssetMaintenanceWorkOrder_organizationId_status_idx" ON "AssetMaintenanceWorkOrder"("organizationId","status"); CREATE INDEX "AssetMaintenanceWorkOrder_assetEntityType_assetEntityId_idx" ON "AssetMaintenanceWorkOrder"("assetEntityType","assetEntityId"); CREATE INDEX "AssetMaintenanceWorkOrder_scheduledStart_idx" ON "AssetMaintenanceWorkOrder"("scheduledStart");
CREATE UNIQUE INDEX "AssetIncident_systemNumber_key" ON "AssetIncident"("systemNumber"); CREATE INDEX "AssetIncident_organizationId_status_idx" ON "AssetIncident"("organizationId","status"); CREATE INDEX "AssetIncident_assetEntityType_assetEntityId_idx" ON "AssetIncident"("assetEntityType","assetEntityId"); CREATE INDEX "AssetIncident_eventId_idx" ON "AssetIncident"("eventId");
CREATE INDEX "AssetDisposal_organizationId_status_idx" ON "AssetDisposal"("organizationId","status"); CREATE INDEX "AssetDisposal_assetEntityType_assetEntityId_idx" ON "AssetDisposal"("assetEntityType","assetEntityId"); CREATE INDEX "AssetGovernanceException_organizationId_resolvedAt_severity_idx" ON "AssetGovernanceException"("organizationId","resolvedAt","severity"); CREATE INDEX "AssetGovernanceException_entityType_entityId_idx" ON "AssetGovernanceException"("entityType","entityId");

ALTER TABLE "AssetDefinition" ADD CONSTRAINT "AssetDefinition_organizationId_fkey" FOREIGN KEY("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AssetDefinition" ADD CONSTRAINT "AssetDefinition_createdByUserId_fkey" FOREIGN KEY("createdByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AssetInstance" ADD CONSTRAINT "AssetInstance_organizationId_fkey" FOREIGN KEY("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AssetInstance" ADD CONSTRAINT "AssetInstance_assetDefinitionId_fkey" FOREIGN KEY("assetDefinitionId") REFERENCES "AssetDefinition"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AssetInstance" ADD CONSTRAINT "AssetInstance_createdByUserId_fkey" FOREIGN KEY("createdByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AssetInstance" ADD CONSTRAINT "AssetInstance_parentInstanceId_fkey" FOREIGN KEY("parentInstanceId") REFERENCES "AssetInstance"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AssetBatch" ADD CONSTRAINT "AssetBatch_organizationId_fkey" FOREIGN KEY("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "AssetBatch" ADD CONSTRAINT "AssetBatch_assetDefinitionId_fkey" FOREIGN KEY("assetDefinitionId") REFERENCES "AssetDefinition"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AssetKit" ADD CONSTRAINT "AssetKit_organizationId_fkey" FOREIGN KEY("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "AssetKit" ADD CONSTRAINT "AssetKit_assetDefinitionId_fkey" FOREIGN KEY("assetDefinitionId") REFERENCES "AssetDefinition"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AssetKitMember" ADD CONSTRAINT "AssetKitMember_assetKitId_fkey" FOREIGN KEY("assetKitId") REFERENCES "AssetKit"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AssetLocation" ADD CONSTRAINT "AssetLocation_parentLocationId_fkey" FOREIGN KEY("parentLocationId") REFERENCES "AssetLocation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AssetOperationLine" ADD CONSTRAINT "AssetOperationLine_assetOperationId_fkey" FOREIGN KEY("assetOperationId") REFERENCES "AssetOperation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
