'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { PageHeader } from '../../../../components/app-shell/page-header';
import { useAppSession } from '../../../../components/app-shell/session-context';
import { createAssetIncident, createAssetOperation, createAssetReservation, getAssetGovernanceSummary, recordAssetDeployment, recordAssetInspection, searchAssets } from '../../../../lib/asset-management-api';
import type { AssetDefinition, AssetGovernanceSummary, AssetSearchResult } from '../../../../lib/asset-management-types';
import { listRequirementSets } from '../../../../lib/event-planning-api';
import type { RequirementItem } from '../../../../lib/event-planning-types';
import { getEvent } from '../../../../lib/events-api';
import type { EventRecord } from '../../../../lib/events-types';

const field = 'rounded-md border border-zinc-300 px-3 py-2 text-sm';

export default function EventAssetsPage() {
  const { id } = useParams<{ id: string }>(); const eventId = String(id); const { session } = useAppSession();
  const options = useMemo(() => ({ token: session.token, baseUrl: session.baseUrl }), [session.baseUrl, session.token]);
  const [eventRecord, setEventRecord] = useState<EventRecord | null>(null); const [assets, setAssets] = useState<AssetSearchResult>({ definitions: [], instances: [] });
  const [requirements, setRequirements] = useState<RequirementItem[]>([]); const [summary, setSummary] = useState<AssetGovernanceSummary | null>(null);
  const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);

  const load = useCallback(async (term = '') => { if (!session.token) return; try { const event = await getEvent(options, eventId); setEventRecord(event); const [found, sets, governance] = await Promise.all([searchAssets(options, event.organizationId, term), listRequirementSets(options, eventId), getAssetGovernanceSummary(options, event.organizationId)]); setAssets(found); setRequirements(sets.filter((set) => set.status === 'Approved').at(0)?.items ?? []); setSummary(governance); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Failed to load event assets.'); } }, [eventId, options, session.token]);
  useEffect(() => {
    // Load the governed event asset workspace.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [load]);

  async function act(work: () => Promise<unknown>, success: string) { setBusy(true); setError(''); setMessage(''); try { await work(); setMessage(success); await load(search); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Asset action failed.'); } finally { setBusy(false); } }
  const organizationId = eventRecord?.organizationId ?? '';

  return <div className="flex flex-col gap-5">
    <PageHeader title="Event Assets" description="Reserve, prepare, deploy and return physical assets with separate availability, condition, custody and lifecycle controls." actions={<Link href={`/events/${eventId}`} className="rounded-md border border-zinc-300 px-3 py-2 text-sm">Back to Event</Link>} />
    {error ? <p role="alert" className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}{message ? <p className="rounded-md bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p> : null}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Asset definitions" value={summary?.definitions ?? 0} /><Metric label="Active reservations" value={count(summary?.reservations, ['Reserved', 'Confirmed'])} /><Metric label="Open incidents" value={count(summary?.incidents, ['Open', 'Investigating', 'RecoveryInProgress'])} /><Metric label="Maintenance work" value={count(summary?.maintenance, ['Approved', 'Scheduled', 'InProgress', 'AwaitingParts'])} /><Metric label="Governance exceptions" value={summary?.unresolvedGovernanceExceptions ?? 0} /></section>
    <form onSubmit={(event) => { event.preventDefault(); void load(search); }} className="flex flex-col gap-2 sm:flex-row"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search asset code, name, serial or QR" className={`${field} min-w-0 flex-1`} /><button className="rounded-md bg-zinc-900 px-4 py-2 text-sm text-white">Search assets</button></form>
    <section className="grid gap-4 lg:grid-cols-2">{assets.definitions.map((asset) => <AssetCard key={asset.id} asset={asset} requirements={requirements} eventRecord={eventRecord} busy={busy} onReserve={(requirementId, quantity) => act(() => createAssetReservation(options, { organizationId, eventId, requirementItemId: requirementId, assetDefinitionId: asset.id, quantity, startDateTime: eventRecord!.startDateTime, endDateTime: eventRecord!.endDateTime }), 'Asset capacity reserved from system-calculated availability.')} onPrepare={(requirementId, quantity) => act(() => createAssetOperation(options, { organizationId, eventId, operationType: 'EventPreparation', lines: [{ requirementItemId: requirementId, assetEntityType: 'AssetDefinition', assetEntityId: asset.id, quantityPlanned: quantity }] }), 'Draft preparation operation created. It still requires operational progression.')} onDeploy={(requirementId, quantity, area) => act(() => recordAssetDeployment(options, { organizationId, eventId, requirementItemId: requirementId, assetEntityType: 'AssetDefinition', assetEntityId: asset.id, quantity, deploymentArea: area, setupStatus: 'Deployed' }), 'Event deployment evidence recorded.')} onInspect={(outcome, notes) => act(() => recordAssetInspection(options, { organizationId, eventId, assetEntityType: 'AssetDefinition', assetEntityId: asset.id, inspectionType: 'EventReturn', outcome, notes }), 'Return inspection recorded. Failed or quarantined serialized assets remain unavailable.')} onIncident={(type, description) => act(() => createAssetIncident(options, { organizationId, eventId, assetEntityType: 'AssetDefinition', assetEntityId: asset.id, incidentType: type, occurredAt: new Date().toISOString(), description }), 'Asset incident recorded for governed follow-up.')} />)}{!assets.definitions.length ? <p className="rounded-xl border bg-white p-5 text-sm text-zinc-600">No matching asset definitions. Create and receive assets in Resources before reserving them for this event.</p> : null}</section>
  </div>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border bg-white p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>; }
function count(rows: Array<{ status: string; _count: number }> | undefined, statuses: string[]) { return rows?.filter((row) => statuses.includes(row.status)).reduce((sum, row) => sum + row._count, 0) ?? 0; }

function AssetCard(props: { asset: AssetDefinition; requirements: RequirementItem[]; eventRecord: EventRecord | null; busy: boolean; onReserve: (requirementId: string, quantity: number) => Promise<void>; onPrepare: (requirementId: string, quantity: number) => Promise<void>; onDeploy: (requirementId: string, quantity: number, area: string) => Promise<void>; onInspect: (outcome: 'Pass' | 'PassWithNotes' | 'Fail' | 'Quarantine', notes: string) => Promise<void>; onIncident: (type: 'Damage' | 'Loss' | 'Missing' | 'Theft' | 'Failure', description: string) => Promise<void> }) {
  const available = props.asset.quantityOnHand - props.asset.quantityUnavailable;
  return <article className="rounded-xl border bg-white p-5"><div className="flex justify-between gap-2"><div><h2 className="font-semibold">{props.asset.name}</h2><p className="text-xs text-zinc-600">{props.asset.assetDefinitionId} · {props.asset.category} · {props.asset.ownershipType}</p></div><span className="rounded-full bg-zinc-100 px-2 py-1 text-xs">{props.asset.trackingMode}</span></div><dl className="mt-3 grid grid-cols-3 gap-2 text-sm"><div><dt className="text-xs text-zinc-500">On hand</dt><dd>{props.asset.quantityOnHand}</dd></div><div><dt className="text-xs text-zinc-500">Unavailable</dt><dd>{props.asset.quantityUnavailable}</dd></div><div><dt className="text-xs text-zinc-500">System available</dt><dd className="font-medium">{available}</dd></div></dl><AssetActionForm asset={props.asset} requirements={props.requirements} busy={props.busy} onReserve={props.onReserve} onPrepare={props.onPrepare} onDeploy={props.onDeploy} onInspect={props.onInspect} onIncident={props.onIncident} /></article>;
}

function AssetActionForm(props: Omit<Parameters<typeof AssetCard>[0], 'eventRecord'>) {
  return <form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const action = String(data.get('action')); const requirementId = String(data.get('requirement')); const quantity = Number(data.get('quantity')); if (action === 'reserve') void props.onReserve(requirementId, quantity); if (action === 'prepare') void props.onPrepare(requirementId, quantity); if (action === 'deploy') void props.onDeploy(requirementId, quantity, String(data.get('notes'))); if (action === 'inspect') void props.onInspect(String(data.get('outcome')) as 'Pass' | 'PassWithNotes' | 'Fail' | 'Quarantine', String(data.get('notes'))); if (action === 'incident') void props.onIncident(String(data.get('incidentType')) as 'Damage' | 'Loss' | 'Missing' | 'Theft' | 'Failure', String(data.get('notes'))); }} className="mt-4 grid gap-2 sm:grid-cols-2"><select required name="action" className={field}><option value="reserve">Reserve capacity</option><option value="prepare">Create preparation operation</option><option value="deploy">Record deployment</option><option value="inspect">Record return inspection</option><option value="incident">Report incident</option></select><select required name="requirement" className={field}><option value="" disabled>Select event requirement</option>{props.requirements.map((item) => <option key={item.id} value={item.id}>{item.requirementCode} · {item.name}</option>)}</select><input required type="number" min="0.0001" step="any" name="quantity" defaultValue="1" aria-label="Quantity" className={field} /><select name="outcome" aria-label="Inspection outcome" className={field}><option>Pass</option><option>PassWithNotes</option><option>Fail</option><option>Quarantine</option></select><select name="incidentType" aria-label="Incident type" className={field}><option>Damage</option><option>Loss</option><option>Missing</option><option>Theft</option><option>Failure</option></select><input name="notes" placeholder="Deployment area, inspection note or incident details" className={field} /><button disabled={props.busy || !props.requirements.length} className="rounded-md bg-zinc-900 px-3 py-2 text-sm text-white disabled:opacity-40 sm:col-span-2">Record controlled asset action</button></form>;
}
