export enum SupplierCategory {
  Venue = 'Venue',
  Catering = 'Catering',
  Decor = 'Decor',
  Photography = 'Photography',
  Videography = 'Videography',
  Entertainment = 'Entertainment',
  DJ = 'DJ',
  Florist = 'Florist',
  AudioVisual = 'AudioVisual',
  EquipmentRental = 'EquipmentRental',
  Security = 'Security',
  Transport = 'Transport',
  Staffing = 'Staffing',
  Accommodation = 'Accommodation',
  Printing = 'Printing',
  Other = 'Other',
}
