import type { EventExecutionWorkspace, ExecutionControlStatus } from './event-execution-workspace-types';
type Options = { token: string; baseUrl: string };
async function request<T>(options: Options, path: string, init?: RequestInit) { const base = options.baseUrl.endsWith('/') ? options.baseUrl.slice(0, -1) : options.baseUrl; const response = await fetch(`${base}${path}`, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${options.token}`, ...(init?.headers ?? {}) }, cache: 'no-store' }); if (!response.ok) { let message = `Request failed with status ${response.status}`; try { const body = (await response.json()) as { message?: string | string[] }; message = Array.isArray(body.message) ? body.message.join(', ') : body.message ?? message; } catch { /* Keep fallback. */ } throw new Error(message); } return (await response.json()) as T; }
const root = (organizationId: string, eventId: string) => `/organizations/${organizationId}/events/${eventId}/execution`;
export const getExecutionWorkspace = (o: Options, org: string, event: string) => request<EventExecutionWorkspace>(o, root(org, event));
export const createExecutionWorkspace = (o: Options, org: string, event: string, summary?: string) => request<EventExecutionWorkspace>(o, root(org, event), { method: 'POST', body: JSON.stringify({ summary }) });
export const buildExecutionPlan = (o: Options, org: string, event: string) => request(o, `${root(org, event)}/plan`, { method: 'POST', body: '{}' });
export const createExecutionTask = (o: Options, org: string, event: string, input: { title: string; description?: string; completionCriteria: string; plannedStart?: string; plannedEnd?: string }) => request(o, `${root(org, event)}/tasks`, { method: 'POST', body: JSON.stringify(input) });
export const changeExecutionTaskStatus = (o: Options, org: string, event: string, taskId: string, status: ExecutionControlStatus, evidenceOrReason?: string) => request(o, `${root(org, event)}/tasks/${taskId}/status`, { method: 'PATCH', body: JSON.stringify({ status, ...(status === 'Completed' ? { completionEvidence: { operatorEvidence: evidenceOrReason } } : {}), ...(status === 'Blocked' ? { blockedReason: evidenceOrReason } : {}) }) });
export const assessExecutionGate = (o: Options, org: string, event: string, input: { key: string; name: string; category: string; decision: 'Pending' | 'Passed' | 'Failed' | 'Waived'; blockerSummary?: string; waiverReason?: string }) => request(o, `${root(org, event)}/gates`, { method: 'POST', body: JSON.stringify(input) });
export const approveExecutionGoLive = (o: Options, org: string, event: string) => request(o, `${root(org, event)}/go-live`, { method: 'POST' });
export const setExecutionRunOfShow = (o: Options, org: string, event: string, items: Array<{ sequence: number; title: string; scheduledAt: string; durationMinutes?: number; cueType?: string }>) => request(o, `${root(org, event)}/run-of-show`, { method: 'POST', body: JSON.stringify({ items }) });
export const recordExecutionCommandLog = (o: Options, org: string, event: string, input: { logType: string; severity: string; message: string }) => request(o, `${root(org, event)}/command-log`, { method: 'POST', body: JSON.stringify(input) });
export const createExecutionIncident = (o: Options, org: string, event: string, input: { incidentType: string; severity: string; title: string; description: string; location?: string }) => request(o, `${root(org, event)}/incidents`, { method: 'POST', body: JSON.stringify(input) });
export const changeExecutionIncidentStatus = (o: Options, org: string, event: string, incidentId: string, status: string) => request(o, `${root(org, event)}/incidents/${incidentId}/status`, { method: 'PATCH', body: JSON.stringify({ status }) });
export const createExecutionCloseoutItem = (o: Options, org: string, event: string, input: { closeoutType: string; criteria: string }) => request(o, `${root(org, event)}/closeout-items`, { method: 'POST', body: JSON.stringify(input) });
export const completeExecutionCloseoutItem = (o: Options, org: string, event: string, itemId: string, status: ExecutionControlStatus) => request(o, `${root(org, event)}/closeout-items/${itemId}`, { method: 'PATCH', body: JSON.stringify({ status, evidence: { operatorConfirmed: true } }) });
export const transitionExecution = (o: Options, org: string, event: string, action: 'dispatch' | 'collect' | 'complete') => request(o, `${root(org, event)}/${action}`, { method: 'POST' });

