import type { FinanceSummary, FinanceWorkspace } from './finance-control-types';
type O={token:string;baseUrl:string}; async function req<T>(o:O,p:string,i?:RequestInit){const b=o.baseUrl.endsWith('/')?o.baseUrl.slice(0,-1):o.baseUrl;const r=await fetch(`${b}${p}`,{...i,headers:{'Content-Type':'application/json',Authorization:`Bearer ${o.token}`,...(i?.headers??{})},cache:'no-store'});if(!r.ok){let m=`Request failed with status ${r.status}`;try{const x=await r.json() as{message?:string|string[]};m=Array.isArray(x.message)?x.message.join(', '):x.message??m}catch{}throw new Error(m)}return await r.json() as T} const root=(org:string,event:string)=>`/organizations/${org}/events/${event}/finance`;
export const getFinanceWorkspace=(o:O,org:string,event:string)=>req<FinanceWorkspace>(o,root(org,event)); export const getFinanceSummary=(o:O,org:string,event:string)=>req<FinanceSummary>(o,`${root(org,event)}/summary`); export const createFinanceWorkspace=(o:O,org:string,event:string,input:{currency:string;statutorySystemName?:string})=>req<FinanceWorkspace>(o,root(org,event),{method:'POST',body:JSON.stringify(input)});
export const createFinanceWbs=(o:O,org:string,event:string,input:{code:string;name:string})=>req(o,`${root(org,event)}/wbs`,{method:'POST',body:JSON.stringify(input)});
export const createFinanceLine=(o:O,org:string,event:string,input:{wbsNodeId:string;lineType:string;stage:string;description:string;quantity?:number;unitAmount:number;taxAmount?:number;currency:string;sourceModule:string;sourceType:string;sourceId:string})=>req<{id:string}>(o,`${root(org,event)}/lines`,{method:'POST',body:JSON.stringify(input)}); export const approveFinanceLine=(o:O,org:string,event:string,id:string)=>req(o,`${root(org,event)}/lines/${id}/approve`,{method:'POST'});
export const createFinanceBudget=(o:O,org:string,event:string,input:{versionType:string;description?:string;lines:Array<{wbsNodeId:string;lineType:string;description:string;amount:number;currency:string}>})=>req(o,`${root(org,event)}/budgets`,{method:'POST',body:JSON.stringify(input)}); export const changeFinanceBudgetStatus=(o:O,org:string,event:string,id:string,status:string,reason?:string)=>req(o,`${root(org,event)}/budgets/${id}/status`,{method:'PATCH',body:JSON.stringify({status,reason})});
export const createFinancialChange=(o:O,org:string,event:string,input:{changeType:string;sourceModule:string;sourceType:string;sourceId:string;description:string;revenueImpact?:number;costImpact?:number;forecastImpact?:number})=>req(o,`${root(org,event)}/changes`,{method:'POST',body:JSON.stringify(input)}); export const approveFinancialChange=(o:O,org:string,event:string,id:string)=>req(o,`${root(org,event)}/changes/${id}/approve`,{method:'POST'});
export const createFinanceCommitment=(o:O,org:string,event:string,input:{supplierId:string;description:string;amountExcludingTax:number;taxAmount?:number;currency:string})=>req(o,`${root(org,event)}/commitments`,{method:'POST',body:JSON.stringify(input)}); export const changeFinanceCommitmentStatus=(o:O,org:string,event:string,id:string,status:string)=>req(o,`${root(org,event)}/commitments/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});
export const createClientInvoice=(o:O,org:string,event:string,input:{contactId:string;invoiceNumber:string;dueDate?:string;currency:string;lines:Array<{description:string;quantity:number;unitPrice:number;taxAmount?:number;sourceType:string;sourceId:string}>})=>req(o,`${root(org,event)}/invoices`,{method:'POST',body:JSON.stringify(input)}); export const changeInvoiceStatus=(o:O,org:string,event:string,id:string,status:string)=>req(o,`${root(org,event)}/invoices/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});
export const createFinancePayment=(o:O,org:string,event:string,input:{invoiceId?:string;commitmentId?:string;direction:string;amount:number;currency:string;plannedDate?:string;bankReference?:string})=>req(o,`${root(org,event)}/payments`,{method:'POST',body:JSON.stringify(input)}); export const changeFinancePaymentStatus=(o:O,org:string,event:string,id:string,status:string)=>req(o,`${root(org,event)}/payments/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});
export const createFinanceReconciliation=(o:O,org:string,event:string,input:{reconciliationType:string;sourceModule:string;sourceType:string;sourceId:string;expectedAmount:number;recordedAmount:number;explanation?:string})=>req(o,`${root(org,event)}/reconciliations`,{method:'POST',body:JSON.stringify(input)}); export const changeFinanceReconciliationStatus=(o:O,org:string,event:string,id:string,status:string,explanation?:string)=>req(o,`${root(org,event)}/reconciliations/${id}/status`,{method:'PATCH',body:JSON.stringify({status,explanation})});
export const createFinanceCloseItem=(o:O,org:string,event:string,input:{closeType:string;criteria:string})=>req(o,`${root(org,event)}/close-items`,{method:'POST',body:JSON.stringify(input)}); export const changeFinanceCloseItem=(o:O,org:string,event:string,id:string,status:string)=>req(o,`${root(org,event)}/close-items/${id}`,{method:'PATCH',body:JSON.stringify({status,evidence:{operatorConfirmed:true}})}); export const closeFinanceWorkspace=(o:O,org:string,event:string)=>req(o,`${root(org,event)}/close`,{method:'POST'});

